### ISSUE TITLE
Links to external services, third-party JS loaded into each request

### ISSUE THREAD

**Issue by HarryR** [adrianchifor/ctrlv.space#1]
Google analytics and fonts are being loaded from third-party domains: fonts.googleapis.com and www.google-analytics.com.

If these can be optional or excluded by default it would make it easier to host a more secure service.

**Comment by adrianchifor** [comment]
Hey @HarryR, thanks for bringing this up. I will put the google analytics before a check as it is optional anyway and bring the font locally.

**Comment by adrianchifor** [comment]
Resolved in 8a32818b6fe7c8a4e1653d43dd9b81733aa26cb9. Will close for now.
